[functions.cron-tasa-bcv]
verify_jwt = false

[functions.notificacion-pago]
verify_jwt = false

[auth]
additional_redirect_urls = [
  "https://domus-ve.vercel.app",
  "https://domus-ve.vercel.app/**",
  "https://domus-ve.vercel.app/reset-password",
  "https://condominio-app-rouge.vercel.app",
  "https://condominio-app-rouge.vercel.app/**",
  "https://condominio-app-rouge.vercel.app/reset-password",
  "http://localhost:5173",
  "http://localhost:5173/**",
  "http://localhost:5173/reset-password",
  "http://localhost:3000",
  "http://localhost:3000/**",
  "http://localhost:3000/reset-password",
  "http://127.0.0.1:5173",
  "http://127.0.0.1:5173/**",
  "http://127.0.0.1:5173/reset-password"
]
site_url = "https://domus-ve.vercel.app"

[auth.email]
max_frequency = "1m0s"
otp_length = 8

[auth.rate_limit]
email_sent = 30

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true
